apiVersion: v1
kind: Pod
metadata:
  annotations:
  generateName: exhort-6f58d7577-
  name: exhort-6f58d7577-mwxd4-debug
  namespace: exhort-test
  labels:
    app: exhort
spec:
  containers:
  - env:
    - name: API_SNYK_HOST
      value: https://app.snyk.io/api/v          
    - name: API_SNYK_TOKEN
      valueFrom:
        secretKeyRef:
          key: api-snyk-token
          name: exhort-secret
    - name: API_OSSINDEX_DISABLED
      value: "true"
    - name: MONITORING_ENABLED
      value: "true"
    - name: MONITORING_SENTRY_DSN
      valueFrom:
        secretKeyRef:
          key: sentry-dsn
          name: exhort-secret
    - name: MONITORING_SENTRY_SERVERNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MONITORING_SENTRY_ENVIRONMENT
      value: development
    - name: TELEMETRY_WRITE_KEY
      valueFrom:
        secretKeyRef:
          key: telemetry-write-key
          name: exhort-secret
    image: quay.io/ecosystem-appeng/exhort:latest
    imagePullPolicy: IfNotPresent
    name: exhort
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 9000
      name: management
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000800000
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gf6rl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-cjkwq
  nodeName: ip-10-0-144-178.eu-north-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000800000
    seLinuxOptions:
      level: s0:c28,c22
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-gf6rl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status: {}
